// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pequeñas porciones para abrir el apetito antes del plato principal.",
                            Name = "Entradas",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Opciones frescas y livianas, ideales como acompañamiento o plato principal.",
                            Name = "Ensaladas",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Platos rápidos y clásicos de bodegón: milanesas, tortillas, revueltos.",
                            Name = "Minutas",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Variedad de pastas caseras y salsas tradicionales.",
                            Name = "Pastas",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cortes de carne asados a la parrilla, servidos con guarniciones.",
                            Name = "Parrilla",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Pizzas artesanales con masa casera y variedad de ingredientes.",
                            Name = "Pizzas",
                            Order = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sandwiches y lomitos completos preparados al momento.",
                            Name = "Sandwiches",
                            Order = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Gaseosas, jugos, aguas y opciones sin alcohol.",
                            Name = "Bebidas",
                            Order = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cervezas de producción artesanal, rubias, rojas y negras.",
                            Name = "Cerveza Artesanal",
                            Order = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Clásicos dulces caseros para cerrar la comida.",
                            Name = "Postres",
                            Order = 10
                        });
                });

            modelBuilder.Entity("Domain.Entities.DeliveryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Delivery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Take away"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dine in"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Dish", b =>
                {
                    b.Property<Guid>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("DishId");

                    b.HasIndex("Category");

                    b.ToTable("Dish", (string)null);

                    b.HasData(
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b001"),
                            Available = true,
                            Category = 8,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Botella de agua sin gas 500ml",
                            ImageUrl = "https://hiperlibertad.vteximg.com.br/arquivos/ids/162797-1000-1000/Agua-mineral-sin-gas-Villavicencio-500-cc-2-5960.jpg?v=637287221936070000",
                            Name = "Agua mineral",
                            Price = 1200m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b002"),
                            Available = true,
                            Category = 1,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tarta casera con calabaza horneada y queso gratinado",
                            ImageUrl = "https://static.wixstatic.com/media/c4453b_f544f31a8b8e483bbda4abc1a509441d~mv2.jpg/v1/fit/w_2500,h_1330,al_c/c4453b_f544f31a8b8e483bbda4abc1a509441d~mv2.jpg",
                            Name = "Tarta de Calabaza y Queso",
                            Price = 1150m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b003"),
                            Available = true,
                            Category = 5,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tiras de costilla de vaca a la parrilla, jugosas y doradas",
                            ImageUrl = "https://bacoclub.com.ar/wp-content/uploads/2022/03/Diseno-sin-titulo-84.png",
                            Name = "Asado de tira",
                            Price = 5500m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b004"),
                            Available = true,
                            Category = 3,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hamburguesa de lentejas con vegetales grillados",
                            ImageUrl = "https://th.bing.com/th/id/R.f1503bcd01728f6753b9f248c976b498?rik=McGsV%2fHuW9E%2bMA&pid=ImgRaw&r=0",
                            Name = "Hamburguesa Vegana",
                            Price = 1200m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b005"),
                            Available = true,
                            Category = 7,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milanesa de carne con lechuga y tomate",
                            ImageUrl = "https://www.infobae.com/resizer/v2/UZIPTP5U5JGKXCIAT35NTWH2OY.jpg?auth=e918349c7ab3c3362141e0871b125f8b0845005fe3755715814e7a1aa9763e1f&smart=true&width=1200&height=1200&quality=85",
                            Name = "Sándwich de milanesa",
                            Price = 2800m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b006"),
                            Available = true,
                            Category = 9,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cerveza roja 500ml",
                            ImageUrl = "https://www.clarin.com/2022/03/09/K6mP1BcmN_2000x1500__1.jpg",
                            Name = "Roja artesanal",
                            Price = 2300m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b007"),
                            Available = true,
                            Category = 4,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ñoquis caseros con mezcla de salsa blanca y tomate",
                            ImageUrl = "https://img.freepik.com/foto-gratis/noquis-salsa-rosa_163431-42.jpg?size=626&ext=jpgg",
                            Name = "Ñoquis con salsa rosa",
                            Price = 1100m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b008"),
                            Available = true,
                            Category = 10,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Torta fría de galletitas de chocolate, dulce de leche y queso crema",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/8/8c/Chocotorta_recipe.png",
                            Name = "Chocotorta",
                            Price = 1400m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b009"),
                            Available = true,
                            Category = 7,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sandwich de lomo, lechuga, tomate, huevo y papas",
                            ImageUrl = "https://canalc.com.ar/wp-content/uploads/2022/04/lomito.jpeg",
                            Name = "Lomito completo",
                            Price = 3200m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b00a"),
                            Available = true,
                            Category = 1,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Empanadas horneadas rellenas de carne y cebolla",
                            ImageUrl = "https://recetasargentinas.net/wp-content/uploads/2014/02/IMG_6988-scaled.jpg",
                            Name = "Empanadas de carne",
                            Price = 1200m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b00b"),
                            Available = true,
                            Category = 1,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tostadas de pan con tomate, ajo y albahaca",
                            ImageUrl = "https://global.filippoberio.com/wp-content/uploads/2018/11/tomatobasilbruschetta.jpg",
                            Name = "Bruschetta",
                            Price = 950m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b00c"),
                            Available = true,
                            Category = 6,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pizza rellena de cebolla y queso",
                            ImageUrl = "https://www.thespruceeats.com/thmb/Rlhhh1kXMArdvRrVSZEkjhTp2-4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/fugazza1-56b549cd5f9b5829f82d3106.jpg",
                            Name = "Fugazzeta",
                            Price = 3600m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b00d"),
                            Available = true,
                            Category = 5,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Matambre a la parrilla con salsa de tomate y queso gratinado",
                            ImageUrl = "https://media.airedesantafe.com.ar/p/b5592bf920dcbb803f78a99a3c8e7903/adjuntos/268/imagenes/003/777/0003777919/1200x675/smart/como-hacer-matambre-la-pizza-casa-la-receta-mas-facil-y-rica.png",
                            Name = "Matambre a la pizza",
                            Price = 5300m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b00e"),
                            Available = true,
                            Category = 6,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pizza con jamón, tomate y huevo duro",
                            ImageUrl = "https://easyways.cl/storage/20210208143331pizza-napolitana.jpg",
                            Name = "Pizza Napolitana",
                            Price = 3800m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b00f"),
                            Available = true,
                            Category = 3,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Huevos revueltos con vegetales frescos",
                            ImageUrl = "https://okdiario.com/img/recetas/2017/01/07/revuelto-de-verduras.jpg",
                            Name = "Revueltos de verduras",
                            Price = 1900m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b010"),
                            Available = true,
                            Category = 3,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tortilla española con papas y cebolla",
                            ImageUrl = "https://alicante.com.ar/wp-content/uploads/2022/06/14_receta-1200x900.jpg",
                            Name = "Tortilla de papas",
                            Price = 2000m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b011"),
                            Available = true,
                            Category = 10,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Torta de chocolate con crema chantilly y cerezas",
                            ImageUrl = "https://petitfitbycris.com/wp-content/uploads/2021/06/TARTA-SELVA-NEGRA.jpg",
                            Name = "Torta selva negra",
                            Price = 1600m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b012"),
                            Available = true,
                            Category = 10,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Brownie caliente con helado de vainilla",
                            ImageUrl = "https://cloudfront-us-east-1.images.arcpublishing.com/elespectador/BS7XK3UP25GMJO3G5IXXDXCRCE.png",
                            Name = "Brownie con helado",
                            Price = 1500m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b013"),
                            Available = true,
                            Category = 10,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Flan casero acompañado con dulce de leche",
                            ImageUrl = "https://tse1.mm.bing.net/th/id/OIP.mouC6Anzrihj38e8HaoAqgHaDt?rs=1&pid=ImgDetMain&o=7&rm=3",
                            Name = "Flan con Dulce de Leche",
                            Price = 5000m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b014"),
                            Available = true,
                            Category = 10,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Base de masa dulce con crema y frutillas frescas",
                            ImageUrl = "https://kobietamag.pl/wp-content/uploads/2016/04/tarta-z-truskawkami-i-bita-smietana-ozdobiona-liscmi-miety.jpg",
                            Name = "Tarta de Frutilla",
                            Price = 1200m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b015"),
                            Available = true,
                            Category = 2,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tomates cherry, aceitunas negras, queso feta, pepino y aceite de oliva",
                            ImageUrl = "https://www.gastrolabweb.com/u/fotografias/m/2021/5/18/f800x450-13354_64800_5942.jpg",
                            Name = "Ensalada Mediterránea",
                            Price = 15000m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b016"),
                            Available = true,
                            Category = 8,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lata de 330ml",
                            ImageUrl = "https://statics.dinoonline.com.ar/imagenes/full_600x600_ma/3080111_f.jpg",
                            Name = "Gaseosa Cola",
                            Price = 900m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b017"),
                            Available = true,
                            Category = 4,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Capas de pasta, salsa bolognesa, bechamel y mucho queso",
                            ImageUrl = "https://www.gourmet.cl/wp-content/uploads/2016/09/iStock-505754880-1.jpg",
                            Name = "Lasagna Bolognesa Garfield",
                            Price = 1600m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b018"),
                            Available = true,
                            Category = 9,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cerveza rubia 500ml",
                            ImageUrl = "https://capacitacioneselmolino.com/wp-content/uploads/2020/07/rubia.png",
                            Name = "Rubia artesanal",
                            Price = 2200m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b019"),
                            Available = true,
                            Category = 8,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Botella 500ml, natural",
                            ImageUrl = "https://buenazo.cronosmedia.glr.pe/original/2022/02/07/62014ff370f93115af6521ad.jpg",
                            Name = "Jugo de naranja",
                            Price = 1500m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b01a"),
                            Available = true,
                            Category = 5,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Queso provolone gratinado con especias",
                            ImageUrl = "https://statics.eleconomista.com.ar/2023/11/654969aa42ec0.jpg",
                            Name = "Provolone a la parrilla",
                            Price = 1500m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b01b"),
                            Available = true,
                            Category = 4,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pasta con crema, queso y manteca",
                            ImageUrl = "https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480_1_5x/img/recipe/ras/Assets/376F934D-2E64-4FC4-A92F-9729A571EA61/Derivates/39233641-090E-46F7-B2E1-7B4E204EB111.jpg",
                            Name = "Fetuccine Alfredo",
                            Price = 2600m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b01c"),
                            Available = true,
                            Category = 4,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ravioles caseros rellenos de ricota y nuez con salsa de tomate",
                            ImageUrl = "https://cdn2.cocinadelirante.com/1020x600/filters:format(webp):quality(75)/sites/default/files/images/2022/03/dia-de-los-ravioles-1.jpg",
                            Name = "Ravioles de Ricota",
                            Price = 1000m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b01d"),
                            Available = true,
                            Category = 9,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cerveza negra 500ml",
                            ImageUrl = "https://media.c5n.com/p/8257e620ec73971b92c765e48bbe38b6/adjuntos/326/imagenes/000/245/0000245175/790x0/smart/cerveza-negra.jpg",
                            Name = "Negra artesanal",
                            Price = 2400m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DishId = new Guid("f0e1e2ab-4c49-496a-8fd5-1ebc0c77b01e"),
                            Available = true,
                            Category = 5,
                            CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bondiola de cerdo marinada y asada a la parrilla",
                            ImageUrl = "https://i.ytimg.com/vi/mydgw6LJQMk/maxresdefault.jpg",
                            Name = "Bondiola",
                            Price = 4800m,
                            UpdateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DeliveryTo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<int>("OverallStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("OrderId");

                    b.HasIndex("DeliveryType");

                    b.HasIndex("OverallStatus");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.Property<long>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderItemId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("Dish")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("Dish");

                    b.HasIndex("Order");

                    b.HasIndex("Status");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "In progress"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ready"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delivery"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Closed"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Dish", b =>
                {
                    b.HasOne("Domain.Entities.Category", "CategoryNavigation")
                        .WithMany("Dishes")
                        .HasForeignKey("Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryNavigation");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.DeliveryType", "DeliveryTypeNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Status", "OverallStatusNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("OverallStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryTypeNavigation");

                    b.Navigation("OverallStatusNavigation");
                });

            modelBuilder.Entity("Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Domain.Entities.Dish", "DishNavigation")
                        .WithMany("OrderItems")
                        .HasForeignKey("Dish")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Order", "OrderNavigation")
                        .WithMany("OrderItems")
                        .HasForeignKey("Order")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Status", "StatusNavigation")
                        .WithMany("OrderItems")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DishNavigation");

                    b.Navigation("OrderNavigation");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("Domain.Entities.DeliveryType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Entities.Dish", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Domain.Entities.Status", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
